name: Ab Hominem
title: Ab Hominem
url: AbHominem.com
markdown: kramdown
permalink: /wiki/:title
gem:
  - jekyll-seo-tag
  - jekyll-sitemap

theme: jekyll-theme-slate
category-list: [Autoimmunity, Cancer, Infection, Transplants, Other]
approval-list: [1985, 1996, 1997, 1998, 2001, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
patent-list: [1985, 1996, 1997, 1998, 2001, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
type-list: [Agonist, Antagonist, ADC, ADCC, TDCC, Imaging, Radiation]
target-list: [Anthrax, C5, CardiacMyosin, CD110, CD11a(LFA-1), CD126(IL-6R), CD152(CTLA-4), CD19, CD20, CD22, CD25(IL-2Rα), CD254(RANKL), CD257(BAFF), CD274(PD-L1), CD279(PD-1), CD2, CD30(TNFRSF8), CD319(SLAMF7), CD33, CD340(HER2), CD38, CD3, CD41(Integrin-α2β), CD52, CD66(CEA), CD80, CD86, Toxin-B, Dabigatran, EGFR, EpCAM, Fprotein(RSV), GD2, IL-12, IL-23, IL-17R, IL-17α, IL-1, IL-1b, IL-4Rα, IL-5, IL-6, IgE-Fc, Integrin-α4, Integrin-α4β7, PCSK9, PDGFRα, PSMA, TNFα, VEGF-A, VEGFR2]